name: my_flutter_template_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  go_router: ^14.1.4
  intl: ^0.19.0
  nayef_common_data_toolkit:
    git:
      url: https://github.com/nayefradwi/nayef_flutter_dart_commons
      path: packages/nayef_common_data_toolkit
      ref: main
  nayef_common_domain_toolkit:
    git:
      url: https://github.com/nayefradwi/nayef_flutter_dart_commons
      path: packages/nayef_common_domain_toolkit
      ref: main
  nayef_common_widgets:
    git:
      url: https://github.com/nayefradwi/nayef_flutter_dart_commons
      path: packages/nayef_common_widgets
      ref: main
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
